### ISSUE TITLE
LightZone does not start after installation on Windows 10

### ISSUE THREAD

**Issue by AlbertFetscher** [AntonKast/LightZone#19]
After installation of LightZone on a Windows 10 laptop, LightZone does not start. 

No error message is shown, no log file is available (or I didn't found one).

Also if I try to start LightZone using Windows cmd.exe (in installation folder of LightZone) nothing happens, no reaction, no message is shown.

Why? What can we do?

**Comment by jedd** [comment]
Hi Albert,

Did you check Documents > LightZone > LightZone.log -- on your C: drive?  That's where the log file on a Microsoft Windows machine should be located, assuming it's getting far enough to actually log anything.  Perhaps check if that directory exists?

You may be able to try running Lightzone as administrator, in case there's some permissions issue.  

I'm not a frequent Microsoft Windows user, so they're my only two suggestions.

**Comment by AlbertFetscher** [comment]
Hi Jedd,

thank you very much for your reply.

a) Yes I checked "Documents > LightZone > LightZone.log" but directory "Documents > LightZone" does not exist.
b) This morning I tried to install Lightzone as administrator, but without success. Same behaviour.

Now I checked drive C: again and searched for any LightZone file, and I found a "error.txt" file in the installation directory "C:\Program Files\LightZone". Content shows an error message during installation (time stamp) as follows:
`
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Component.<clinit>(Component.java:626)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:51)
	at com.lightcrafts.platform.windows.WindowsLauncher.main(WindowsLauncher.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
`

**Comment by jedd** [comment]
Hi Albert,

Could you please clarify which version of the JRE you've got installed on that system?

**Comment by AlbertFetscher** [comment]
Hi Jedd,

no extra JRE is installed on the system (laptop, Windows 10 Home).
During the installation of Lightzone, the JRE version 11.0.9 was created in the "C:\Program Files\LightZone\jre\bin" directory.
`
C:\Program Files\LightZone\jre\bin>java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment JBR-11.0.9.11-1145.10-jcef (build 11.0.9+11-b1145.10)
OpenJDK 64-Bit Server VM JBR-11.0.9.11-1145.10-jcef (build 11.0.9+11-b1145.10, mixed mode) 
`

**Comment by jedd** [comment]
Okay, thanks - beyond my troubleshooting abilities, but that info will help others hopefully.  : )

If you're bored, you may care to download and install the Microsoft release of OpenJDK - either 11 or 17 seems to be long-term-support versions.  I suspect both would work, but on my Debian box here I'm using v11 without issue.

**Comment by AlbertFetscher** [comment]
Thank you very much for your help, Jedd.

I was not bored but tried to downloaded and install JDK 17. 
`
C:\Users\Gabi>java -version
java version "17.0.3" 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)
`

Did re-install LightZone but without success. Same behaviour and error log:
[error.log](https://github.com/AntonKast/LightZone/files/8553774/error.log)

Thanks for your tips and hints.

**Comment by ktgw0316** [comment]
@AlbertFetscher I guess there is some trouble loading dependent dll(s) for the JRE.  Could you try to find out which one is missing?

1. Download [Dependencies](https://github.com/lucasg/Dependencies/releases) tool (Dependencies_x64_Release.zip)
2. Execute DependenciesGui.exe
3. Open ```C:\Program Files\LightZone\jre\bin\jawt.dll```
4. Check if there is something missing in the dependency tree

**Comment by AlbertFetscher** [comment]
@ktgw0316 Thank you vey much for your feedback.
I followed your instructions 1-4, and Dependencies tool indicates "could not be found on disc":
a) ext-ms-win-oobe-query-l1-1-0.dll
b) jvm.dll

**Comment by ktgw0316** [comment]
Hmm... These "missing" jvm.dll and \*-ms-win-\*.dll are false positive in general case, and they are not found on my machine either.  Now I have no idea what causes the error.

By the way, you said that version of ```jre/bin/java``` is "11.0.9", but it should be "11.0.13" for the latest LightZone (v4.2.4).  I updated the bundled JRE version in 943aa92, so I guess you are using LZ v4.2.3.  Could you install and test the latest one?
https://github.com/ktgw0316/LightZone/releases/tag/4.2.4

**Comment by AlbertFetscher** [comment]
OK, I installed the latest version of LightZone 4.2.4. 
Result is:
a) After installation no error message has been reported. That's good.
b) After start of LightZone nothing happens (maybe one or two seconds mouse cursor indicates busy). LightZone did not run, no error message was shown nor reported.

Now I have also no idea what could cause the problem.
It would be fine if an error report (error.log in a specific directory or something like that) was available.
